apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: YOUR_NAME-cronjob
  labels:
    app: YOUR_NAME
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: YOUR_NAME-cronjob
            image: YOUR_IMAGE
            envFrom:
            - configMapRef:
                name: YOUR_NAME-configmap
          restartPolicy: Never
