apiVersion: v1
kind: Service
metadata:
  name: YOUR_NAME-service
spec:
  ports:
    - name: YOUR_NAME-http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: YOUR_NAME
  type: NodePort